name: app_rickandmorty
description: "2024. Nikitos - (c) Big project Big problem"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  core_app:
    path: packages/core_app
  ui_kit_app:
    path: packages/ui_kit_app
  models_app:
    path: packages/models_app
  
  app_runner: 2.2.2
  logger: 1.4.0
  # rxdart: 0.28.0
  mobx: 2.3.3+2
  flutter_mobx: 2.2.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.0
  build_runner: 2.4.11
  mobx_codegen: 2.6.1


flutter:
  uses-material-design: true



# [✓] Flutter (Channel stable, 3.22.2, on macOS 15.0.1 24A348 darwin-arm64,
#     locale ru-US)
#     • Flutter version 3.22.2 on channel stable at
#       /Users/<USER>/Documents/dev/flutter
#     • Upstream repository https://github.com/flutter/flutter.git
#     • Framework revision 761747bfc5 (5 months ago), 2024-06-05 22:15:13
#       +0200
#     • Engine revision edd8546116
#     • Dart version 3.4.3
#     • DevTools version 2.34.3

# [✓] Android toolchain - develop for Android devices (Android SDK version
#     34.0.0)
#     • Android SDK at /Users/<USER>/Library/Android/sdk
#     • Platform android-34, build-tools 34.0.0
#     • Java binary at: /Applications/Android
#       Studio.app/Contents/jbr/Contents/Home/bin/java
#     • Java version OpenJDK Runtime Environment (build
#       17.0.6+0-17.0.6b802.4-9586694)
#     • All Android licenses accepted.

# [✓] Xcode - develop for iOS and macOS (Xcode 16.0)
#     • Xcode at /Applications/Xcode.app/Contents/Developer
#     • Build 16A2d
#     • CocoaPods version 1.15.2

# [✓] Chrome - develop for the web
#     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

# [✓] Android Studio (version 2022.2)
#     • Android Studio at /Applications/Android Studio.app/Contents
#     • Flutter plugin can be installed from:
#       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
#     • Dart plugin can be installed from:
#       🔨 https://plugins.jetbrains.com/plugin/6351-dart
#     • Java version OpenJDK Runtime Environment (build
#       17.0.6+0-17.0.6b802.4-9586694)

# [✓] VS Code (version 1.94.2)
#     • VS Code at /Applications/Visual Studio Code.app/Contents
#     • Flutter extension version 3.98.0

# [✓] Connected device (3 available)
#     • macOS (desktop)                 • macos                 • darwin-arm64
#       • macOS 15.0.1 2448 darwin-arm64
#     • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin
#       • macOS 15.0.1 2438 darwin-arm64
#     • Chrome (web)                    • chrome                •
#       web-javascript • Google Chrome 129.0.6668.101
