name: ui_kit_app
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  shimmer: 3.0.0
  cached_network_image: 3.4.1
  custom_refresh_indicator: 4.0.1
  flutter_svg: 2.0.10+1
  # cupertino_icons: 1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.0
  flutter_gen_runner: 5.7.0
  build_runner: 2.4.11


flutter_gen:
  output: lib/src/generated/ # Optional (default: lib/gen/)
  line_length: 100 # Optional (default: 80)
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true