name: core_app
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  logger: 1.4.0
  ### Optimization request server
  # async: 2.11.0
  # pool: 1.5.1
  rxdart: 0.28.0
  ## Database 
  shared_preferences: 2.3.2

  models_app:
    path: ../models_app
  client_rickandmorty:
    path: ../client_rickandmorty


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.0
