name: core_app
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  logger: 1.4.0
  ### Optimization request server
  async: 2.11.0
  pool: 1.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.0
