name: client_rickandmorty
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  dio: 5.4.0
  pretty_dio_logger: 1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.0
